- README.md
- beautysh/beautysh.py
Add special comments to turn on and off formatting. Modeled
after the Eclipse formatter support
command \
--option1 \
--option2 \
--option3 \
Allows skipping any code that breaks formatter. :-)
Signed-off-by: Jhon Honce <jhonce@redhat.com>
> Turn on/off formatting

- beautysh/beautysh.py
Modeled after the TLDP advanced bash scripting guide
http://tldp.org/LDP/abs/html/testbranch.html#EX29
Before:
```
case "${blah}" in
one) make alpha ;;
two)
make beta;;
twoandahalf)
case "${blue}" in
four) make alpha ;;
five)
make beta;;
six)
make alpha
make beta
make release
;;
esac
three)
make alpha
make beta
make release
;;
esac
```
After:
```
case "${blah}" in
one) make alpha ;;
two)
make beta ;;
twoandahalf)
case "${blue}" in
four) make alpha ;;
five)
make beta ;;
six)
make alpha
make beta
make release
;;
esac
three)
make alpha
make beta
make release
;;
esac
```
Ensuring the space before a `;;` isn't the example found in TLDP advanced bash scripting guide, but I do feel it makes the code more readable and consistent.
> Improve case statement formatting

- .pre-commit-hooks.yaml
I'd like to use beautysh as a [pre-commit hook](https://pre-commit.com/) for some shell script projects. To use this hook in a repo, create a `.pre-commit-config.yaml` in the repo root with the following, then run `pre-commit install --install-hooks`.
```
repos:
- repo: https://github.com/bemeurer/beautysh
sha: 3.5 # or whatever tag this change might be released in
hooks:
- id: beautysh
```
> Add a pre-commit config so beautysh can be used as a pre-commit hook

- beautysh/beautysh.py
The output of beautysh currently outputs indentation on lines that are otherwise blank. Most engineers I know have their editors set to strip whitespace from the end of lines. This change ensures that blank lines remain so.
> Ensure that blank lines are preserved without adding indentation

- beautysh/beautysh.py
As mentioned in https://docs.python.org/2/library/re.html:
> The solution is to use Python’s raw string notation for regular expression patterns; backslashes are not handled in any special way in a string literal prefixed with 'r'. So r"\n" is a two-character string containing '\' and 'n', while "\n" is a one-character string containing a newline. Usually patterns will be expressed in Python code using this raw string notation.
> Using raw strings for regular expressions is best practice

- beautysh/beautysh.py
Before:
```
help() {
####### help text
cat - <<ENDHELP
All your help here
ENDHELP
exit 0
}
```
After:
```
help() {
####### help text
cat - <<ENDHELP
All your help here
ENDHELP
exit 0
}
```
> Indent the command that starts a heredoc

- beautysh/beautysh.py
This change should fix issues with while loops formatted the following way:
```
while read -r thing; do
echo "$thing done"
done <<< $filename
```
beautysh.py was parsing that `<<< $filename` as a heredoc delimiter, enabling a heredoc paragraph that was never being closed.
And that was the cause for the error message of those indent/outdent mismatch: the indentation was the same as the one in `done <<< $filename` till the end of file.
Now, before enabling heredoc, we double check if it really isn't a while case.
This should fix #23.
> Prevent specific while loop to be recognized as heredoc

- beautysh/beautysh.py
I ran into the issue described in issue #11.  One of the comments in that thread says that:
> The problem is indeed the <<< here-string syntax. Beautysh mostly assumes that any appearance of << indicates a here document, which is false. The above commit changed beautysh to exclude a very specific use of here strings (i.e., the ones at the ends of while loops), but doesn't address broader use of here strings.
As far as I can tell, excluding all instances of here-strings should be fine.  It certainly fixed my problem.
> here strings not just after loops

- beautysh/beautysh.py
> Add --check cmd line option

- beautysh/beautysh.py
- tests/indent_test1_beautified.sh
- tests/indent_test1_raw.sh
Today I found a weird case inside a shell script that was puzzling beautysh.
The root problem was a string written on multiple lines (using line continuation \) and that was containing brackets. This was causing beautysh indentation logic to fail.
I tried to fix the issue (see new testcase with EVIL_STRING) but I could not understand the code
```
+ (1 if continue_line and not open_brackets else 0)
```
in "extab" computation so for now I simply removed it (otherwise the unit test fails)...
> Add new testcase about multiline lines

- beautysh/beautysh.py
- tests/func_styles_beautified_style0.sh
- tests/func_styles_beautified_style1.sh
- tests/func_styles_beautified_style2.sh
- tests/func_styles_raw.sh
- tests/test_beautysh.py
This PR is the first attempt to fix #32
> Function style fixer

- README.md
I missed some more references of wrong usage in the earlier commit(https://github.com/lovesegfault/beautysh/commit/df515a7f739630864d20835650c4e275de946bce). I am addressing them now.
> Update README.md with correct usage instructions

- README.md
Users would get confused if "Running" section shows some unworkable instruction. We should put it back on README once PackageControl thing is done.
> Remove "Running" from README

- beautysh/beautysh.py
Make the ad-hoc oudent (added in #2) apply only when `elif` is followed by `then` on the same line. In my testing, this addresses #57 without breaking the #2 test case. I'm sure the regex could be cleaned up, though.
> Fix outdent issues for elif (#2, #57)

- flake.nix
Fixes: dot escape.
```
beautysh = beautysh.packages.x86_64-linux."beautysh-python3.8";  
```
> flake: add flattenTree for packages

- flake.lock
| SHA256                                                                                               | Commit Message                                                                  |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------- |
| [`846b2ae0`](https://github.com/numtide/flake-utils/commit/846b2ae0fc4cc943637d3d1def4454213e203cba) | `Update default.nix (#42)`                                                      |
| [`3f197dc7`](https://github.com/numtide/flake-utils/commit/3f197dc7591cc6edc83e1eb44698283c19fd28a2) | `add system map for convenience (#55)`                                          |
| …
> chore(flake/flake-utils): `7e5bf392` -> `846b2ae0`

- flake.lock
| SHA256                                                                                                    | Commit Message                                                                                            |
| --------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------- |
| [`ea15a005`](https://github.com/nix-community/poetry2nix/commit/ea15a00506d0c183064cbc73b687c6be1c0c36b0) | `A few fixes to various packages`                                                                         |
| [`bd2ada93`](https://github.com/nix-community/poetry2nix/commit/bd2ada9339215992913b0f9fa145d2e33a570adb) | `Add mkdocs-jupyter` …
> chore(flake/poetry2nix): `705cbfa1` -> `5aa37b8a`

- flake.lock
| SHA256                                                                                         | Commit Message                                                         |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------- |
| [`d67ad28f`](https://github.com/NixOS/nixpkgs/commit/d67ad28fc301305baeeb364a04f0565c5f5118c8) | `go_1_18: init at go1.18beta1`                                         |
| [`af3cd7c1`](https://github.com/NixOS/nixpkgs/commit/af3cd7c1f80738cc6ef4512cfa8d0bbfc45a88db) | `go: Fix the build in non-root sandboxes`                              |
| [`30ea86e2`](https://github.com/NixOS/nixpkgs/commit/30ea86e22dbc144583d45b43ca2ca42d6ac161dc) | `binlore: …
> chore(flake/nixpkgs): `e4ef597e` -> `5c9b6ab9`

- flake.lock
| SHA256                                                                                         | Commit Message                                                                         |
| ---------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------- |
| [`8cec3cc2`](https://github.com/NixOS/nixpkgs/commit/8cec3cc29e2bc2a7dea71de46d3fd4441700de2e) | `vimPlugins.vim-nixhash: init at 2022-02-06`                                           |
| [`32d2af12`](https://github.com/NixOS/nixpkgs/commit/32d2af12f242bfc87cb67fc4337afd9d15b3f809) | `vimPlugins: update`                                                                   |
| …
> chore(flake/nixpkgs): `5c9b6ab9` -> `8cec3cc2`

- flake.lock
| SHA256                                                                                                    | Commit Message                                       |
| --------------------------------------------------------------------------------------------------------- | ---------------------------------------------------- |
| [`9d6a48c4`](https://github.com/nix-community/poetry2nix/commit/9d6a48c4554d043af9e0c4ebff107b4e3bdf2db5) | `tests.assorted-pkgs: Add mypy test`                 |
| [`43c600f3`](https://github.com/nix-community/poetry2nix/commit/43c600f3901236abd3971fcbf974c28fc52dc560) | `More various fixes`                                 |
| [`31effa4e`](https://github.com/nix-community/poetry2nix/commit/31effa4e4ef6df999b6f03449998b0b7ac6b0923) | `Add hook to remove normal …
> chore(flake/poetry2nix): `5aa37b8a` -> `d3dc8d28`

- flake.lock
| SHA256                                                                                                    | Commit Message                                         |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------------------ |
| [`f36a1aae`](https://github.com/nix-community/poetry2nix/commit/f36a1aaea3198a845e2b48b7a5e71faba52ced45) | `overrides.pymediainfo: patch libmediainfo paths`      |
| [`b92a0073`](https://github.com/nix-community/poetry2nix/commit/b92a007388508dff2b24621821a3e76a7f4057f8) | `overrides.pikepdf: add qpdf and pybind11 buildInputs` |
| [`02926081`](https://github.com/nix-community/poetry2nix/commit/029260810c585af62873752d7c3a186e0db3e286) | …
> chore(flake/poetry2nix): `d3dc8d28` -> `69cc39aa`

- flake.lock
| SHA256                                                                                         | Commit Message                                                                       |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------ |
| [`ab34433b`](https://github.com/NixOS/nixpkgs/commit/ab34433bc0dcdf9b3cfbc8bb187030920b4c0e7b) | `emojipick: init at 2021-01-27 (#158187)`                                            |
| [`53e70ab7`](https://github.com/NixOS/nixpkgs/commit/53e70ab75490df87a165d704a9e98312b3f5137b) | `maintainers/teams: add minijackson to the beam team`                                |
| …
> chore(flake/nixpkgs): `8cec3cc2` -> `21968db3`

- flake.lock
| SHA256                                                                                         | Commit Message                                                           |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------ |
| [`0a2ae8bc`](https://github.com/NixOS/nixpkgs/commit/0a2ae8bc533dc4320f8460949ec154398800fb09) | `gh: 2.6.0 -> 2.7.0`                                                     |
| [`90c46e80`](https://github.com/NixOS/nixpkgs/commit/90c46e80c66d1616882ea472d536e5c3f8a7857a) | `python310Packages.huawei-lte-api: 1.5.4 -> 1.6`                         |
| [`b2635c2b`](https://github.com/NixOS/nixpkgs/commit/b2635c2b71150ec1ab0e3a591685f653b5db7485) | …
> chore(flake/nixpkgs): `21968db3` -> `10632447`

- flake.lock
| SHA256                                                                                                    | Commit Message                                                              |
| --------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------- |
| [`53b790e5`](https://github.com/nix-community/poetry2nix/commit/53b790e5e35506c1232f7dd4c935ae690849e916) | `poetry: 1.1.12 -> 1.1.13`                                                  |
| [`77355835`](https://github.com/nix-community/poetry2nix/commit/7735583527afc000b70759b93c94d35cdc24f2d3) | `overrides.cryptography: Add 36.0.2 hash`                                   |
| …
> chore(flake/poetry2nix): `69cc39aa` -> `2ef1c4d8`

- flake.lock
| SHA256                                                                                                    | Commit Message                                                                  |
| --------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------- |
| [`639115b8`](https://github.com/nix-community/poetry2nix/commit/639115b897676e00a584372fcfbca2efc3894764) | `overrides.lsassy: Work around upstream missing version constraint in setup.py` |
| [`b742ddd0`](https://github.com/nix-community/poetry2nix/commit/b742ddd0876368fc96aa233c15553a34094aaa47) | `overrides.pysrp: Add poetry-core`                                              |
| …
> chore(flake/poetry2nix): `2ef1c4d8` -> `ece2a416`

- flake.lock
| SHA256                                                                                         | Commit Message                                                                   |
| ---------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------- |
| [`6cf368ed`](https://github.com/NixOS/nixpkgs/commit/6cf368ed0e35e71118a35d8896f64e0d00c5161e) | `ocamlPackages.tezos: remove`                                                    |
| [`f26f7a16`](https://github.com/NixOS/nixpkgs/commit/f26f7a16d04c428ea01a7f332f79f5d3c6ae50c8) | `fluxcd: 0.29.3 -> 0.29.4`                                                       |
| [`1248ea16`](https://github.com/NixOS/nixpkgs/commit/1248ea16e1a2009de …
> chore(flake/nixpkgs): `10632447` -> `6766fb65`

- flake.lock
| SHA256                                                                                               | Commit Message                                                                   |
| ---------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------- |
| [`1ed9fb19`](https://github.com/numtide/flake-utils/commit/1ed9fb1935d260de5fe1c2f7ee0ebaae17ed2fa1) | `Fix check-utils template directory name (#70)`                                  |
| [`04c1b180`](https://github.com/numtide/flake-utils/commit/04c1b180862888302ddfb2e3ad9eaa63afc60cf8) | `feat: add convenience eachDefaultSystemMap (#60)`                               |
| …
> chore(flake/utils): `a4b154eb` -> `1ed9fb19`

- flake.lock
| SHA256                                                                                                    | Commit Message                                                                      |
| --------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------- |
| [`a5455bae`](https://github.com/nix-community/poetry2nix/commit/a5455baee32078985bb31b16461b833592fcd1b1) | `Add pytest-runner to plux build inputs`                                            |
| [`42e72813`](https://github.com/nix-community/poetry2nix/commit/42e72813e9415ddb42215d9800efae4cf2cfde98) | `Add pytest-runner to py-multihash build inputs`                                    |
| …
> chore(flake/poetry2nix): `ece2a416` -> `3b01c3e3`

- flake.lock
| SHA256                                                                                               | Commit Message                                                 |
| ---------------------------------------------------------------------------------------------------- | -------------------------------------------------------------- |
| [`32dc3d46`](https://github.com/numtide/flake-utils/commit/32dc3d46b2854de460e1a0d03cea472fafea5acd) | `filterPackages: Fix a typo in the comment`                    |
| [`3b6a41d7`](https://github.com/numtide/flake-utils/commit/3b6a41d794bf4217b353f8b5477f903841a300fb) | `filterPackages: Do not use meta.hydraPlatforms for filtering` |
| [`3ff4550a`](https://github.com/numtide/flake-utils/commit/3ff4550a66be41ea42dfdd0393744623d00c0559) | …
> chore(flake/utils): `1ed9fb19` -> `bee6a725`

- flake.lock
| SHA256                                                                                         | Commit Message                                                                      |
| ---------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------- |
| [`b44f6df4`](https://github.com/NixOS/nixpkgs/commit/b44f6df49725d9d968dc14e97cfcb0d21f8368d3) | `nix-update: 0.5.1 -> 0.6.0`                                                        |
| [`a1aed2a7`](https://github.com/NixOS/nixpkgs/commit/a1aed2a716ff3471f91f0ba57f551335202df98b) | `builders/writeHaskell: build with threaded GHC runtime`                            |
| …
> chore(flake/nixpkgs): `49a2bcc6` -> `f72be3af`

- flake.lock
| SHA256                                                                                                    | Commit Message                                                                   |
| --------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------- |
| [`a6480f2c`](https://github.com/nix-community/poetry2nix/commit/a6480f2ce6d776b27d3be4d98b663e13af5017ca) | `fix: also ignore typing-extensions when resolving dependencies`                 |
| [`f0ef50e3`](https://github.com/nix-community/poetry2nix/commit/f0ef50e3de77a6135c7ad6466b5b78369ca71a03) | `build-systems: add hatchling explicitly for jsonschema >= 4.6.0`                |
| …
> chore(flake/poetry2nix): `3b01c3e3` -> `abc47c71`

- flake.lock
| SHA256                                                                                                    | Commit Message                                                        |
| --------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------- |
| [`5d341161`](https://github.com/nix-community/poetry2nix/commit/5d3411617719b5a6471ccb684e0104a2e35121f2) | ``overrides.tqdm: fix `overrideAttrs` to `overridePythonAttrs```      |
| [`f839d908`](https://github.com/nix-community/poetry2nix/commit/f839d908f0b1e774e969aceccd7d7f0e451ef35f) | `nixpkgs-fmt overrides/default`                                       |
| [`0ba51886`](https://github.com/nix-community/poetry2nix/commit/0ba518 …
```
> chore(flake/poetry2nix): `abc47c71` -> `8b8edc85`

- flake.lock
| SHA256                                                                                               | Commit Message                                       |
| ---------------------------------------------------------------------------------------------------- | ---------------------------------------------------- |
| [`7e2a3b3d`](https://github.com/numtide/flake-utils/commit/7e2a3b3dfd9af950a856d66b0a7d01e3c18aa249) | `check-utils: use the same success derivation (#75)` |
> chore(flake/utils): `bee6a725` -> `7e2a3b3d`

- flake.lock
| SHA256                                                                                               | Commit Message                                                     |
| ---------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------ |
| [`6ee9ebb6`](https://github.com/numtide/flake-utils/commit/6ee9ebb6b1ee695d2cacc4faa053a7b9baa76817) | `Bump cachix/install-nix-action from 17 to 18 (#81)`               |
| [`c0e246b9`](https://github.com/numtide/flake-utils/commit/c0e246b9b83f637f4681389ecabcb2681b4f3af0) | `Update each-system template to use new flake output system (#76)` |
> chore(flake/utils): `7e2a3b3d` -> `6ee9ebb6`

- flake.lock
| SHA256                                                                                               | Commit Message                   |
| ---------------------------------------------------------------------------------------------------- | -------------------------------- |
| [`5aed5285`](https://github.com/numtide/flake-utils/commit/5aed5285a952e0b949eb3ba02c12fa4fcfef535f) | `remove 20 years old arch (#82)` |
> chore(flake/utils): `6ee9ebb6` -> `5aed5285`

- flake.lock
| SHA256                                                                                               | Commit Message                                                 |
| ---------------------------------------------------------------------------------------------------- | -------------------------------------------------------------- |
| [`93a2b84f`](https://github.com/numtide/flake-utils/commit/93a2b84fc4b70d9e089d029deacc3583435c2ed6) | `Update README to reflect example for eachDefaultSystem (#90)` |
| [`3db36a8b`](https://github.com/numtide/flake-utils/commit/3db36a8b464d0c4532ba1c7dda728f4576d6d073) | `Bump cachix/install-nix-action from 18 to 19 (#87)`           |
> chore(flake/utils): `5aed5285` -> `93a2b84f`
